### ISSUE TITLE
Missing descVersion

### ISSUE THREAD

**Issue by SoloTwo** [RealismusModding/FS17_RM_DisableMissions#6]
Not sure if this mod is meant to be used by the general public but it was too good to pass up.  

Only, the problem is it's throwing me this error and doesn't load. 

Error: C:/Users/Shawn/Documents/My Games/FarmingSimulator2017/mods/FS17_RM_NoMissions/modDesc.xml. . .
Load mod: FS17_RM_NoMissions
Error: Missing descVersion attribute in mod FS17_RM_NoMissions

**Comment by joskuijpers** [comment]
The latest update should have fixed it :)

**Comment by SoloTwo** [comment]
Works great, I probably should've noticed that extra space when trying to fix it on my own. :)
